export enum Job {
    ORDER_CONFIRMATION_EMAIL_DIGEST = "ORDER_CONFIRMATION_EMAIL_DIGEST",
    ABANDONED_CART_NOTIFIER = "ABANDONED_CART_NOTIFIER",
    ABANDONED_CART_CHECKER = 'ABANDONED_CART_CHECKER'
}